import Image from "next/image";
import React from "react";
import img from "../../../public/img1.jpg";
export const metadata = {
  title: "About us",
  description: "Generated by create next app",
};

const about = () => {
  return (
    <div className="p-2">
      <h2>About Page</h2>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ad magni,
        repudiandae perspiciatis ex dolorem. Nostrum delectus ab consectetur
        quibusdam accusamus nisi saepe consequuntur quis magni obcaecati et,
        nihil fuga, debitis officiis. Nulla illum vero corporis sapiente
        adipisci id nostrum autem incidunt dolore dignissimos, aut repellendus
        sequi maiores ipsa excepturi!
      </p>
      <div>
        <Image className="h-[700px] object-cover" src={img} alt="map" />
      </div>
    </div>
  );
};

export default about;
